// Code generated by gen-mode.
// mode.json
// DO NOT EDIT

package main

import (
	"fmt"
	"os"
)

const ENV_MODE = "MODE"

const (
	DebugMode      string = "debug"
	ProductionMode string = "production"
	TestMode       string = "test"
)

var modeName string = DebugMode

func Mode() string {
	return modeName
}

func init() {
	mode := os.Getenv(ENV_MODE)
	if len(mode) == 0 {
		SetMode(DebugMode)
	} else {
		SetMode(mode)
	}
}

func SetMode(value string) {
	switch value {
	case DebugMode:
		fmt.Println("Running on Debug")
	case ProductionMode:
		fmt.Println("Running on Production")
	case TestMode:
		fmt.Println("Running on Test")
	default:
		panic("mode unknown: " + value)
	}
	modeName = value
}

func IsDebug() bool {
	return Mode() == DebugMode
}

func IsProduction() bool {
	return Mode() == ProductionMode
}

func IsTest() bool {
	return Mode() == TestMode
}
